#' Generates the post-processing R script
#'
#' Generates an R script that converts raw DIA-NN + MSDAP output into the
#' exact files consumed by app.R's Shiny dashboard:
#'   {jobname}_BasicStats.csv, {jobname}_NormalizedAbundances.csv,
#'   {jobname}_DEA_long.csv, {jobname}_UniqueProteins.csv,
#'   {jobname}_chromatograms_page1-n.png, {jobname}_results.xlsx/.zip
#'   
#' It is a helper function for the processDiannMSdap.R function and MUST run
#' AFTER generateMsdapScript.R.
#'
#' Note: This code has been partially generated by ClaudeCode mixing gsptools custom functions.
#'
#' @param inputPath Path with report.tsv (diann), sample_metadata.xlsx, FASTA, contrasts.csv.
#' @param outputPath Path where msdap_results/ lives and where plots/tables are written.
#' @param jobname Job identifier, e.g. "PROT-1256". Used for output filenames.
#' @return Creates an R script to run post-processing analysis.
#' @keywords internal
#' @noRd

generatePostprocessingScript <- function(inputPath, outputPath, jobname) {

  msdap_path  <- file.path(outputPath, "msdap_results")
  plots_path  <- file.path(outputPath, "plots")
  tables_path  <- file.path(outputPath, "tables")
  report_path <- here::here(inputPath, "report.tsv")
  metadata_path <- here::here(inputPath, "sample_metadata.xlsx")

  glue::glue(r'(
# ================================================================
# Post-processing: DIA-NN report.tsv + MSDAP output -> Shiny inputs
# ================================================================
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)
library(writexl)
library(ggplot2)

jobname     <- "<<jobname>>"
msdap_path  <- "<<msdap_path>>"
plots_path  <- "<<plots_path>>"
tables_path <- "<<tables_path>>"
metadata_path  <- "<<metadata_path>>"
report_path <- "<<report_path>>"
inputPath <- "<<inputPath>>"
outputPath <- "<<outputPath>>"
dir.create(plots_path, recursive = TRUE, showWarnings = FALSE)
dir.create(tables_path, recursive = TRUE, showWarnings = FALSE)

# ----------------------------------------------------------------
# 1) BasicStats.csv  (PSMs / protein groups per raw file)
#    Source: DIA-NN main report.tsv (stable column names, no guessing)
# ----------------------------------------------------------------
report <- fread(report_path)

basic_stats <- report %>%
  mutate(spectrum_file = basename(tools::file_path_sans_ext(Run))) %>%
  group_by(spectrum_file) %>%
  summarise(
    psms           = dplyr::n(),                      # precursor-level identifications
    protein_groups = dplyr::n_distinct(Protein.Group),
    .groups = "drop"
  )

fwrite(basic_stats, file.path(tables_path, paste0(jobname, "_BasicStats.csv")))

# ----------------------------------------------------------------
# 2) NormalizedAbundances.csv
#    Source: MSDAP wide protein-abundance table (output_abundance_tables=TRUE)
# NOTE - verify: the filename pattern/column names against your msdap_results/
# ----------------------------------------------------------------
metadata <- readxl::read_excel(metadata_path)
lookup <- setNames(metadata$shortname, metadata$sample_id)

abundance_file <- list.files(msdap_path,
                              pattern = "protein_abundance__global data filter.tsv",
                              full.names = TRUE, recursive = TRUE)[1]

abundance <- fread(abundance_file) %>%
  select(-fasta_headers) %>%
  rename("protein_name" = gene_symbols_or_id) %>%
  filter(!str_detect(protein_name, "^contam") | is.na(protein_name))
setnames(abundance, old = names(lookup), new = lookup, skip_absent = TRUE)

name_col <- intersect(c("gene_symbol", "protein_name", "symbol", "Genes"), names(abundance))[1]
sample_cols <- setdiff(names(abundance), c("protein_id", "protein_name", name_col))

norm_out <- abundance %>%
  select(protein_id, protein_name, all_of(sample_cols))

fwrite(norm_out, file.path(tables_path, paste0(jobname, "_NormalizedAbundances.csv")))

# ----------------------------------------------------------------
# 3) DEA_long.csv
#    Source: MSDAP long-format DEA table (one row per protein x contrast x algorithm)
# NOTE - verify: the filename pattern/column names against your msdap_results/
# ----------------------------------------------------------------

# Load protein names to put back in DEA
protein_file <- list.files(msdap_path,
                              pattern = "^proteins.tsv.gz",
                              full.names = TRUE, recursive = TRUE)[1]

proteins <- fread(protein_file) %>%
  select(protein_id, gene_symbols) %>%
  mutate(gene_symbols = case_when(
    gene_symbols == "-" ~ protein_id,
    TRUE ~ gene_symbols
  )) %>%
  rename("protein_name" = gene_symbols)

# For differential detection (dd)
dd_file <- list.files(msdap_path,
                        pattern = "^dd_proteins.*\\.tsv",
                        full.names = TRUE, recursive = TRUE)[1]

dd <- fread(dd_file) %>%
  filter(pass_filters == TRUE & abs(log2fc) >= 1) %>%
  mutate(contrast = str_remove(contrast, "^contrast:\\s*"),
         contrast = str_remove(contrast, "\\s*#.*$"),
         dea_algorithm = "differential_detection",
         adj.P.Val = 0) %>%
  rename(
    logFC     = log2fc
  ) %>%
  mutate(logFC = -logFC) %>% # necessary since MSDap does B/A from the contrast name
  left_join(proteins %>% select(protein_id, protein_name), by = "protein_id") %>%
  select(contrast, protein_id, protein_name, logFC, adj.P.Val, dea_algorithm )

dea_file <- list.files(msdap_path,
                        pattern = "^de_proteins.*\\.tsv",
                        full.names = TRUE, recursive = TRUE)[1]

dea <- fread(dea_file)

dea_long <- dea %>%
  rename(
    logFC     = foldchange.log2,
    adj.P.Val = pvalue
  ) %>%
  mutate(logFC = -logFC) %>% # necessary since MSDap does B/A from the contrast name
  left_join(proteins %>% select(protein_id, protein_name), by = "protein_id") %>%
  mutate(protein_name = coalesce(protein_name, protein_id)) %>%
  select(contrast, protein_id, protein_name, logFC, adj.P.Val, dea_algorithm) %>%
  mutate(contrast = str_remove(contrast, "^contrast:\\s*"),
         contrast = str_remove(contrast, "\\s*#.*$")) %>%
  bind_rows(., dd)

fwrite(dea_long, file.path(tables_path, paste0(jobname, "_DEA_long.csv")))

# individual tables for each contrast
wide <- dea_long %>%
  pivot_wider(
    id_cols = c(contrast, protein_id, protein_name),
    names_from = dea_algorithm,
    values_from = c(logFC, adj.P.Val)
  )

# Taking significance between all 3 algorithms
# (differential_detection is optional - not every job's postprocessing includes it,
#  e.g. it's disabled via diffdetect_min_peptides_observed = NA upstream in MSDAP)
has_diffdetect <- "logFC_differential_detection" %in% colnames(wide)

sig_in_all <- wide %>%
  group_by(protein_id, protein_name) %>%
  mutate(
    sig_by_dea = (abs(logFC_deqms) >= 1 & abs(logFC_msempire) >= 1 & abs(logFC_msqrob) >= 1 &
                    adj.P.Val_deqms <= 0.01 &
                    adj.P.Val_msempire <= 0.01 & adj.P.Val_msqrob <= 0.01),
    sig_by_diffdetect = if (has_diffdetect) abs(logFC_differential_detection) >= 1 else FALSE,
    sig_in_all = case_when(
      # coalesce to FALSE so a stray NA in any comparison doesn't silently
      # drop the row from the OR entirely
      coalesce(sig_by_dea, FALSE) | coalesce(sig_by_diffdetect, FALSE) ~ "Significant",
      TRUE ~ "Non-Significant"
    )
  ) %>%
  filter(sig_in_all == "Significant") %>%
  select(-sig_by_dea, -sig_by_diffdetect) %>%
  ungroup()

split_tables <- sig_in_all %>%
  group_split(contrast) %>%
  setNames(sort(unique(sig_in_all$contrast))) %>%
  setNames(snakecase::to_snake_case(names(.)))

# ----------------------------------------------------------------
# 4) UniqueProteins.csv
#    Proteins DIA-NN detected in the raw search but MSDAP dropped during
#    filtering (insufficient replicates/quant) - not present in the
#    normalized matrix used for stats, but still worth reporting.
# ----------------------------------------------------------------
raw_ids  <- unique(report$Protein.Group)
kept_ids <- unique(norm_out$protein_id)
dropped_ids <- setdiff(raw_ids, kept_ids)

unique_proteins <- report %>%
  filter(Protein.Group %in% dropped_ids, !is.na(PG.MaxLFQ), PG.MaxLFQ > 0) %>%
  mutate(sample_id = basename(tools::file_path_sans_ext(Run))) %>%
  left_join(metadata %>% select(sample_id, group), by = "sample_id") %>%
  group_by(Protein.Group) %>%
  summarise(
    protein_name    = dplyr::first(Genes),
    n_groups_detected = dplyr::n_distinct(group),
    detected_in      = paste(unique(group), collapse = "; "),
    .groups = "drop"
  ) %>%
  rename(protein_id = Protein.Group) %>%
  filter(n_groups_detected <= 1)

fwrite(unique_proteins, file.path(tables_path, paste0(jobname, "_UniqueProteins.csv")))

# ----------------------------------------------------------------
# 5) Chromatogram PNGs
# ----------------------------------------------------------------

mzML_files <- list.files(inputPath, pattern = "\\.mzML$", full.names = TRUE)
chromatogram_list <- vector("list", length(mzML_files))

    for(i in 1:length(mzML_files)){

      msdata <- RaMS::grabMSdata(mzML_files[i], grab_what = "TIC")

      p <- ggplot(msdata$TIC, aes(x = rt, y = int)) +
        geom_line(color = "black", linewidth = 0.4) +        # thin line like instrument software
        geom_area(fill = "black") +         # filled area under the curve
        scale_y_continuous(
          expand = expansion(mult = c(0, 0.05)),             # start y-axis at 0
          labels = scales::scientific                         # scientific notation on y-axis
        ) +
        scale_x_continuous(
          expand = expansion(mult = c(0.01, 0.01))           # minimal padding on x-axis
        ) +
        labs(
          x = "Retention Time (min)",
          y = "Intensity",
          title = paste0(sub("_uncalibrated.\\mzML$", "\\1", basename(mzML_files[i])), " TIC")
        ) +
        theme_classic() +                                    # clean white background, no gridlines
        theme(
          axis.line = element_line(color = "black", linewidth = 0.5),
          axis.ticks = element_line(color = "black"),
          axis.text = element_text(color = "black", size = 10),
          axis.title = element_text(color = "black", size = 11),
          plot.title = element_text(hjust = 0.5, size = 12)  # centered title
        )

      chromatogram_list[[i]] <- p

      rm(msdata, p)
      gc()
      }

# --- Classify each mzML file by name so chromatograms can be paged into
#     separate QC / Blank / Samples PDFs-as-PNGs instead of one mixed set.
#     "hela" wins over "blank" if a filename somehow matched both. ---
file_group <- dplyr::case_when(
  str_detect(basename(mzML_files), regex("hela", ignore_case = TRUE)) ~ "QC",
  str_detect(basename(mzML_files), regex("blank", ignore_case = TRUE)) ~ "Blank",
  TRUE ~ "Samples"
)

# Split the (already-rendered) plot list into the three groups, keeping
# plots in the same order they were generated.
grouped_plots <- split(chromatogram_list, file_group)

# Split into chunks of 4 and write pages, per group. Groups with 0 files
# just produce no pages (split() on an empty list yields an empty list, so
# the inner loop simply doesn't run for them).
for (grp_name in names(grouped_plots)) {

  grp_list <- grouped_plots[[grp_name]]
  chunks <- split(grp_list, ceiling(seq_along(grp_list) / 4))

  for (i in seq_along(chunks)) {
    png(here::here(plots_path, paste0(jobname, "_chromatograms_", grp_name, "_page", i, ".png")),
        units = "in", res = 300, width = 8, height = 11)

    p <- cowplot::plot_grid(plotlist = chunks[[i]], ncol = 1)
    print(p)

    dev.off()
  }
}

# ----------------------------------------------------------------
# 6) Combined results.xlsx + results.zip for the "Download results" tab
# ----------------------------------------------------------------
write_xlsx(
  c(
    list(
      Description           = data.frame(Sheet = c("BasicStats", "NormalizedAbundances", "UniqueProteins", "DEA_long", "Sig_in_all_algorithms", "Human readable contrasts"),
                                          Description = c("PSMs / protein groups per raw file",
                                                           "Normalized log2 protein abundances per sample",
                                                           "Unique proteins per group",
                                                          "Differential expression results, long format",
                                                          "Proteins considered significant in all algorithms, a.k.a. the most confident hits",
                                                          "Individual tables for each contrast with logFC and p-values from all algorithms, only includes proteins that are significant in all groups")),
      BasicStats             = basic_stats,
      NormalizedAbundances   = norm_out,
      UniqueProteins         = unique_proteins,
      DEA_long               = dea_long,
      Sig_in_all_algorithms  = sig_in_all
    ),
  split_tables
  ),
  path = file.path(tables_path, paste0(jobname, "_results.xlsx"))
)

zip::zip(
  zipfile = file.path(tables_path, paste0(jobname, "_results.zip")),
  files   = list.files(tables_path, full.names = TRUE),
  mode    = "cherry-pick"
)

message("=== Post-processing complete: files written to ", plots_path, " ===")
  )', .open = "<<", .close = ">>")
}
